# Generated by Django 5.1.6 on 2025-07-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_readingpassage_content_hash_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readingpassage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='question',
            name='blank_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='readingpassage',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
