# Generated by Django 5.2.5 on 2025-08-21 21:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0003_delete_dailytestrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='測驗日期')),
                ('mixed_test_count', models.IntegerField(default=0, verbose_name='綜合測驗次數')),
                ('other_part_test_count', models.IntegerField(default=0, verbose_name='單一Part測驗次數')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '每日測驗紀錄',
                'verbose_name_plural': '每日測驗紀錄',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
