# Generated by Django 5.2.5 on 2025-08-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0005_alter_pointtransaction_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('english_passage', models.TextField()),
                ('chinese_translation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='reason',
            field=models.CharField(choices=[('exam_exchange', '測驗次數兌換'), ('test_completion', '完成測驗'), ('other', '其他')], max_length=255),
        ),
    ]
