# Generated by Django 5.2.5 on 2025-08-21 21:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='英文單字')),
                ('pronunciation', models.CharField(blank=True, max_length=100, verbose_name='音標')),
                ('part_of_speech', models.CharField(max_length=50, verbose_name='詞性')),
                ('translation', models.CharField(max_length=255, verbose_name='中文翻譯')),
                ('example_sentence', models.TextField(verbose_name='例句')),
                ('example_translation', models.TextField(blank=True, null=True, verbose_name='例句翻譯')),
                ('difficulty_level', models.IntegerField(default=1, verbose_name='難度等級')),
                ('related_category', models.CharField(blank=True, choices=[('Business', '商業與職場'), ('Technology', '科技與資訊'), ('DailyLife', '日常生活'), ('Academic', '學術與教育'), ('Travel', '旅遊與文化')], default='DailyLife', max_length=100, verbose_name='主題類別')),
            ],
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='vocab_score',
        ),
        migrations.RemoveField(
            model_name='listeningmaterial',
            name='source',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_e_text',
        ),
        migrations.RemoveField(
            model_name='readingpassage',
            name='source',
        ),
        migrations.AddField(
            model_name='listeningmaterial',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listeningmaterial',
            name='translation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('format_error', '格式有誤'), ('wrong_part', '不符合相對應 Part'), ('content_error', '內文有誤'), ('question_error', '題目有誤')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='translation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='learning_interests',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('reading', 'Reading'), ('listen', 'Listening'), ('mixed', 'Mixed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='part',
            field=models.IntegerField(blank=True, choices=[(0, 'All - 綜合測驗'), (2, 'Part 2 - 應答問題'), (3, 'Part 3 - 簡短對話'), (5, 'Part 5 - 句子填空'), (6, 'Part 6 - 段落填空'), (7, 'Part 7 - 單篇閱讀')], null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='listen_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='reading_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='total_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='time_limit_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listeningmaterial',
            name='accent',
            field=models.CharField(blank=True, choices=[('british', 'British'), ('american', 'American'), ('australian', 'Australian'), ('canadian', 'Canadian')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listeningmaterial',
            name='audio_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='part',
            field=models.IntegerField(blank=True, choices=[(0, 'All - 綜合測驗'), (2, 'Part 2 - 應答問題'), (3, 'Part 3 - 簡短對話'), (5, 'Part 5 - 句子填空'), (6, 'Part 6 - 段落填空'), (7, 'Part 7 - 單篇閱讀')], null=True),
        ),
        migrations.CreateModel(
            name='DailyTestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='測驗日期')),
                ('mixed_test_count', models.IntegerField(default=0, verbose_name='綜合測驗次數')),
                ('other_part_test_count', models.IntegerField(default=0, verbose_name='單一Part測驗次數')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '每日測驗紀錄',
                'verbose_name_plural': '每日測驗紀錄',
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserVocabularyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_familiar', models.BooleanField(default=False, verbose_name='是否熟悉')),
                ('last_viewed', models.DateTimeField(auto_now=True, verbose_name='最後檢視時間')),
                ('sent_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='單字發送時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toeic.dailyvocabulary', verbose_name='單字')),
            ],
            options={
                'verbose_name': '使用者單字紀錄',
                'verbose_name_plural': '使用者單字紀錄',
                'unique_together': {('user', 'word')},
            },
        ),
    ]
