# Generated by Django 5.2.5 on 2025-08-21 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0002_dailyvocabulary_remove_examresult_vocab_score_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyTestRecord',
        ),
    ]
