# Generated by Django 5.2.5 on 2025-08-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0004_dailytestrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtransaction',
            name='reason',
            field=models.CharField(choices=[('exam_exchange', '測驗次數兌換'), ('other', '其他')], max_length=255),
        ),
    ]
