# Generated by Django 5.2.5 on 2025-08-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0006_phrase_alter_pointtransaction_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytestrecord',
            name='mixed_test_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dailytestrecord',
            name='other_part_test_limit',
            field=models.IntegerField(default=3),
        ),
    ]
