# Generated by Django 5.2.6 on 2025-09-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toeic", "0008_phrase_title_translation"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_num",
            field=models.IntegerField(blank=True, null=True, verbose_name="題號"),
        ),
    ]
