# Generated by Django 5.2.1 on 2025-10-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0009_question_question_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='part',
            field=models.IntegerField(blank=True, choices=[(0, 'All - 綜合測驗'), (2, 'Part 2 - 應答問題'), (3, 'Part 3 - 簡短獨白'), (5, 'Part 5 - 句子填空'), (6, 'Part 6 - 段落填空'), (7, 'Part 7 - 單篇閱讀')], null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='part',
            field=models.IntegerField(blank=True, choices=[(0, 'All - 綜合測驗'), (2, 'Part 2 - 應答問題'), (3, 'Part 3 - 簡短獨白'), (5, 'Part 5 - 句子填空'), (6, 'Part 6 - 段落填空'), (7, 'Part 7 - 單篇閱讀')], null=True),
        ),
    ]
